### ISSUE TITLE
Is dit echt een lijst?

### ISSUE THREAD

**Issue by KrijnHoetmer** [christoph3r3w/MiddenWest-client-website#1]
Complicated, I know :) But isn't everything a list, in a way? Isn't a sentence a list of words? And a word a list of characters? :)

https://github.com/christoph3r3w/the-client-website/blob/3bdccc62d02499002eae48ce48d7f52caaf7d94f/index2.html#L22-L24

**Comment by christoph3r3w** [comment]
everything can be a list indeed, maar mijn design is veranderd, dus een lijst is hier niet meer nodig

**Comment by christoph3r3w** [comment]
also solved
