### ISSUE TITLE
Multiple h2's

### ISSUE THREAD

**Issue by KrijnHoetmer** [christoph3r3w/MiddenWest-client-website#2]
Maar er lijkt een h1 te ontbreken? Wat is de belangrijkste heading van je site?

https://github.com/christoph3r3w/the-client-website/blob/3bdccc62d02499002eae48ce48d7f52caaf7d94f/index2.html#L27

**Comment by christoph3r3w** [comment]
yes indeed, I was unsure about my design at that moment, so some elements were placeholders.

**Comment by christoph3r3w** [comment]
fixed now
