### ISSUE TITLE
Divitis...

### ISSUE THREAD

**Issue by KrijnHoetmer** [christoph3r3w/MiddenWest-client-website#3]
Heb je echt zoveel div's nodig? Zie https://css-tricks.com/how-to-section-your-html/

https://github.com/christoph3r3w/the-client-website/blob/3bdccc62d02499002eae48ce48d7f52caaf7d94f/index2.html#L21-L26

**Comment by christoph3r3w** [comment]
actually, I didn't need them. I think I have a better way now.

**Comment by christoph3r3w** [comment]
solved
